# Generated by Django 4.2.25 on 2025-10-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('partial', 'Partielle'), ('overdue', 'En retard')], default='pending', max_length=16)),
                ('due_date', models.DateField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='leasing.leasecontract')),
            ],
            options={
                'unique_together': {('lease', 'period')},
            },
        ),
    ]
