# Generated by Django 4.2.25 on 2025-10-24 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parties.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('person', 'Personne'), ('company', 'Entreprise')], max_length=16)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_landlord', models.BooleanField(default=False, help_text='Legacy: préférez les rôles via Party.roles')),
                ('is_tenant', models.BooleanField(default=False, help_text='Legacy: préférez les rôles via Party.roles')),
                ('is_agent', models.BooleanField(default=False, help_text='Legacy: préférez les rôles via Party.roles')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Rôle de partie',
                'verbose_name_plural': 'Rôles de partie',
            },
        ),
        migrations.CreateModel(
            name='PartyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag de partie',
                'verbose_name_plural': 'Tags de partie',
            },
        ),
        migrations.CreateModel(
            name='PartyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=parties.models.attachment_upload_to)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='parties.party')),
            ],
            options={
                'verbose_name': 'Pièce jointe (Partie)',
                'verbose_name_plural': 'Pièces jointes (Partie)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='party',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='parties', to='parties.partyrole'),
        ),
        migrations.AddField(
            model_name='party',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('agent_of', 'Agent de'), ('legal_rep_of', 'Représentant légal de'), ('employee_of', 'Employé de'), ('family_of', 'Lien familial avec'), ('other', 'Autre')], max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('from_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='parties.party')),
                ('to_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='parties.party')),
            ],
            options={
                'verbose_name': 'Relation entre parties',
                'verbose_name_plural': 'Relations entre parties',
                'indexes': [models.Index(fields=['relation_type'], name='parties_par_relatio_8c8ccd_idx')],
                'unique_together': {('from_party', 'to_party', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='PartyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='parties.party')),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='parties.partytag')),
            ],
            options={
                'verbose_name': 'Note (Partie)',
                'verbose_name_plural': 'Notes (Partie)',
                'indexes': [models.Index(fields=['is_pinned'], name='parties_par_is_pinn_928360_idx'), models.Index(fields=['created_at'], name='parties_par_created_6eabe0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('website', 'Site web'), ('other', 'Autre')], default='phone', max_length=16)),
                ('label', models.CharField(blank=True, help_text='Ex: perso, bureau, WhatsApp…', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('value', models.CharField(blank=True, help_text='Pour website/autres', max_length=255)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='parties.party')),
            ],
            options={
                'verbose_name': 'Contact de partie',
                'verbose_name_plural': 'Contacts de partie',
                'indexes': [models.Index(fields=['type'], name='parties_par_type_a629b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('primary', 'Principale'), ('billing', 'Facturation'), ('mailing', 'Courrier'), ('work', 'Professionnelle'), ('other', 'Autre')], default='primary', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_links', to='accounts.address')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_addresses', to='parties.party')),
            ],
            options={
                'verbose_name': 'Adresse de partie',
                'verbose_name_plural': 'Adresses de partie',
                'indexes': [models.Index(fields=['address_type'], name='parties_par_address_d1d8d4_idx'), models.Index(fields=['is_primary'], name='parties_par_is_prim_31d372_idx')],
                'unique_together': {('party', 'address', 'address_type')},
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['type'], name='parties_par_type_7c8bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['full_name'], name='parties_par_full_na_255e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['email'], name='parties_par_email_bc805c_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['phone'], name='parties_par_phone_d7b480_idx'),
        ),
    ]
