# Generated by Django 4.2.25 on 2025-11-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('cta', models.CharField(default='Voir', max_length=64)),
                ('to', models.CharField(default='/#listings', max_length=200)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('image', models.URLField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapTeaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('to', models.CharField(default='/#map', max_length=200)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=80)),
                ('to', models.CharField(max_length=200)),
                ('gradient', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
    ]
