# Generated by Django 4.2.25 on 2025-11-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['label'], 'verbose_name': 'Équipement', 'verbose_name_plural': 'Équipements par unité'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'l’unité louable/vendable (studio A, appart B, chambre…)'},
        ),
        migrations.AddField(
            model_name='listing',
            name='property_city',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_district',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['property_city', 'property_district'], name='properties__propert_5283ed_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district'], name='properties__distric_2e026e_idx'),
        ),
    ]
